### ISSUE TITLE
Pig-Mode on Emacs 23

### ISSUE THREAD

**Issue by eyala** [motus/pig-mode#23]
I've tried running pig-mode on Emacs 23.1.1 on Centos (manually installing, not using ELPA) and I get this error:

_Symbol's value as variable is void: pig-snippets.el_

With Emacs 24.3.1 on Ubuntu 14.04 the manual installation works fine. Is pig-mode supposed to run on Emacs 23? If not, can you add this to the README? :-)

Thanks!

**Comment by ayman** [comment]
Are you missing the snippets file?

**Comment by eyala** [comment]
I don't remember what I did when I wrote this (it was more than two years ago) but it appears to work now. Maybe I indeed forgot to copy the snippets file.
